spring:
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
    # PostgreSQL配置示例
    postgresql:
      driver-class-name: org.postgresql.ds.PGSimpleDataSource
      url: jdbc:postgresql://192.168.56.36:5432/postgres
      username: postgres
      password: 123456

    # MySQL配置示例
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.56.36:3306/mytest?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456

  data:
    mongodb:
      uri: mongodb://admin:admin@192.168.56.36:27017/mydata
    redis:
      host: 192.168.56.36
      port: 6379
      password:
      database: 0
      timeout: 5000ms
      jedis:
        pool:
          max-active: 8 # 连接池最大连接数(使用负值表示没有限制)
          max-wait: -1ms # 连接池最大阻塞等待时间(使用负值表示没有限制)
          max-idle: 8 # 连接池中的最大空闲连接
          min-idle: 0 # 连接池中的最小空闲连接

mybatis:
  mapper-locations: classpath:mappers/mysql/*.xml,classpath:mappers/postgresql/*.xml,  # 指定MyBatis Mapper XML文件的位置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 用于输出MyBatis日志到控制台